-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PortfolioPerformance.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PortfolioPerformance.InputObject
import PortfolioPerformance.Interface
import PortfolioPerformance.Object
import PortfolioPerformance.Scalar
import PortfolioPerformance.ScalarCodecs
import PortfolioPerformance.Union


created_at : SelectionSet (Maybe String) PortfolioPerformance.Object.User
created_at =
    Object.selectionForField "(Maybe String)" "created_at" [] (Decode.string |> Decode.nullable)


email : SelectionSet (Maybe String) PortfolioPerformance.Object.User
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


first_name : SelectionSet (Maybe String) PortfolioPerformance.Object.User
first_name =
    Object.selectionForField "(Maybe String)" "first_name" [] (Decode.string |> Decode.nullable)


id : SelectionSet String PortfolioPerformance.Object.User
id =
    Object.selectionForField "String" "id" [] Decode.string


last_name : SelectionSet (Maybe String) PortfolioPerformance.Object.User
last_name =
    Object.selectionForField "(Maybe String)" "last_name" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe String) PortfolioPerformance.Object.User
updated_at =
    Object.selectionForField "(Maybe String)" "updated_at" [] (Decode.string |> Decode.nullable)


websocket_connection_ids : SelectionSet (Maybe (List (Maybe String))) PortfolioPerformance.Object.User
websocket_connection_ids =
    Object.selectionForField "(Maybe (List (Maybe String)))" "websocket_connection_ids" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


websocket_connections : SelectionSet decodesTo PortfolioPerformance.Object.WebsocketConnection -> SelectionSet (Maybe (List (Maybe decodesTo))) PortfolioPerformance.Object.User
websocket_connections object_ =
    Object.selectionForCompositeField "websocket_connections" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
