-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PortfolioPerformance.Object exposing (..)


type Allocation
    = Allocation


type PortfolioState
    = PortfolioState


type SubscribedQuery
    = SubscribedQuery


type User
    = User


type WebsocketConnection
    = WebsocketConnection
